version: '3.8'

services:
  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest
  rabbitmq:
    image: rabbitmq:3-management-alpine
      
  catalog-api:
    image: ${REGISTRY:-eshop}/catalog.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile.dev
    depends_on: 
      - sqldata
      - rabbitmq